### PR TITLE
Added reptile objects

### PR DESCRIPTION
**Pull request by idacarlin95**
Please check it looks ok

### CODE REVIEW

**Review by jasminedns — CHANGES_REQUESTED** [review]
We'd need the image of the animal too

**Comment by idacarlin95** [comment]
Fixed images links

**Review by jasminedns — APPROVED** [review]
looks good

**Review by potnurusrilatha — APPROVED** [review]
looks good

**Comment by potnurusrilatha** [comment]
I looked again missed semi column at line 23 ,please check once. Other than that looks good

**Pull request merged**
