### PR TITLE
Added mammels.css file into project

### PR DESCRIPTION
**Pull request by TobiasKjernell**
Added mammels file into project ( into styles folder )

### CODE REVIEW

**Review by idacarlin95 — APPROVED** [review]
Looks good

**Review by jasminedns — APPROVED** [review]
good

**Review by potnurusrilatha — APPROVED** [review]

**Comment by potnurusrilatha** [comment]
perfect

**Review by Moon2024-light — COMMENTED** [review]
looks good!

**Review by Moon2024-light — APPROVED** [review]
good work!

**Review by Moon2024-light — APPROVED** [review]
good work!

**Pull request merged**
